### ISSUE TITLE
About AppSplitter two tag.

### ISSUE THREAD

**Issue by MarsZone** [OnsenUI/vue-onsenui-kitchensink#5]
```
<menu-page></menu-page>
<app-tabbar></app-tabbar>
```
I don't know why this two tag will auto fit to components: { AppTabbar, MenuPage }?
I can't find out these two tag documents anywhere.
Could you help?

**Comment by frandiox** [comment]
Those two tags are Vue components created in this application. [MenuPage is here](https://github.com/OnsenUI/vue-onsenui-kitchensink/blob/master/src/pages/Menu.vue) and [AppTabbar is here](https://github.com/OnsenUI/vue-onsenui-kitchensink/blob/master/src/AppTabbar.vue). The are imported with `import AppTabbar from '...'`, etc.
