### ISSUE TITLE
Android device back button exits app

### ISSUE THREAD

**Issue by jacedh1** [OnsenUI/vue-onsenui-kitchensink#7]
When you build this project and upload it to Monaca the Android back button always exits the app when pressed. My understanding is that the default behaviour should be that the back button should pop the current page if there are more than 1 page in the stack, otherwise it should exit the app.

If you go from "Home" to "Dialogs" and press the back button the app exits, shouldn't it go back to "Home" instead?

Any workarounds for this?

**Comment by frandiox** [comment]
@jacedh1 This is just sample app for browsers so it is not including `cordova.js` (is 404 in browsers). Without that file, it won't be able to fire device back buttons. Simply add `<script src="cordova.js"></script>` in your `index.html` and it will work. If you are using Monaca, you can add `<script src="loader.js"></script>` instead and it will also include `cordova.js`.

**Comment by jacedh1** [comment]
@frandiox Thank you! I had a feeling it was something simple like that!

I had to change the src to "./components/loader.js" but it works like a charm now. Feels like it improved performance too.
